version: '3.3'

services:
  postgresql:
    image: postgres:12.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: demo_password
      POSTGRES_DB: Bank
    restart: always
    volumes:
      - bank_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  bank_data:
